### ISSUE TITLE
Paper UI on Safari (iOS, iPad): Layout corrupted by displaced hide icon

### ISSUE THREAD

**Issue by Boby71** [openhab/openhab2-addons#1303]
![img_3039](https://cloud.githubusercontent.com/assets/22266373/19208437/1ccd0ec0-8cfa-11e6-837e-988f6f8f935a.PNG)

**Comment by kaikreuzer** [comment]
Please report at https://github.com/eclipse/smarthome/issues as this is there Paper UI lives.
Maybe also try the very latest OH2 distro, since there were quite a few fixes the last days in the Paper UI - maybe your issue is already addressed as well.

**Comment by Boby71** [comment]
OK, done: https://github.com/eclipse/smarthome/issues/2285
Still the same problem, even with the newest daily buid from today.

2016-10-08 9:53 GMT+02:00 Kai Kreuzer <notifications@github.com>:
