### ISSUE TITLE
[rfxcom] Connection to RFXCOM transceiver failed

### ISSUE THREAD

**Issue by bricolo100** [openhab/openhab2-addons#1312]
When trying to connect manually to RFXTRX, the following error occurs:

with RFXtrx433E USB 433.92MHz Transceiver

> [INFO ] [ernal.connector.RFXComJD2XXConnector] - Connecting to RFXCOM device 'A12U0A1' using JD2XX.
> [ERROR] [g.rfxcom.handler.RFXComBridgeHandler] - Connection to RFXCOM transceiver failed
> java.io.IOException: device not found (2)
> at jd2xx.JD2XX.openEx(Native Method)[201:org.openhab.binding.rfxcom:2.0.0.201610081754]

with RFXCOM USB Transceiver (port /dev/ttyUSB1)

> 2016-10-10 23:24:15.174 [ERROR] [g.rfxcom.handler.RFXComBridgeHandler] - Connection to RFXCOM transceiver failed: invalid port

I'm running openhab2 on raspberry pi.

**FTDI SIO module is not deselected because I use a modbus USB stick that has a ftdi chip inside** 

RFXCOM module is detected by the system and linked with /dev/ttyUSB1

---
## If i put the ftdi_sio in the blacklist and reboot (but I don't want that because of the other usb stick)

the dmesg is the following

> [    5.261370] usb 1-1.4.1.3: New USB device found, idVendor=0403, idProduct=6001
> [    5.270479] usb 1-1.4.1.3: New USB device strings: Mfr=1, Product=2, SerialNumber=3
> [    5.281455] usb 1-1.4.1.3: Product: RFXtrx433
> [    5.287566] usb 1-1.4.1.3: Manufacturer: RFXCOM
> [    5.293819] usb 1-1.4.1.3: SerialNumber: A12U0A1

no item appears in /dev related to the rfxtrx

and the logs shows (with or without adding the libftd2xx fron ftdi website)

> auto discovery don't workError occured during discovery
> java.io.IOException: device not found (2)
>         at jd2xx.JD2XX.listDevices(Native Method)
>         at jd2xx.JD2XX.listDevicesByDescription(JD2XX.java:826)
>         at org.openhab.binding.rfxcom.internal.discovery.RFXComBridgeDiscovery.discoverRfxcom(RFXComBridgeDiscovery.java:90)

when configuring manually

> [INFO ] [ernal.connector.RFXComJD2XXConnector] - Connecting to RFXCOM device 'A12U0A1' using JD2XX.
> 2016-10-10 23:44:00.702 [ERROR] [g.rfxcom.handler.RFXComBridgeHandler] - Connection to RFXCOM transceiver failed
> java.io.IOException: device not found (2)
>         at jd2xx.JD2XX.openEx(Native Method)[201:org.openhab.binding.rfxcom:2.0.0.201610081754]
>         at jd2xx.JD2XX.openBySerialNumber(JD2XX.java:806)[201:org.openhab.binding.rfxcom:2.0.0.201610081754]
##

**Comment by paulianttila** [comment]
ftdi_sio is not probably enough, you should disable also usbserial, at least application note says so.

http://www.ftdichip.com/Support/Documents/AppNotes/AN_220_FTDI_Drivers_Installation_Guide_for_Linux.pdf

If you don't want disable ftdi_sio, you could always use serial port communication rather than JD2XX. You just need to add "RFXCOM USB Transceiver" bridge manually.

**Comment by don41382** [comment]
```# sudo chmod 777 /dev/ttyUSB0``` did the trick for me

**Comment by martinvw** [comment]
@bricolo100 is this still a problem for you did the tip of @don41382 help you out?

**Comment by McNetic** [comment]
I've got the same problem with openHAB 2.1. I use a RFXtrx433E on a beaglebone black. By default, I get usbserial and ftdi_sio kernel modules, resulting in the rfcxom to be available as /dev/ttyUSB0.

 I manually installed openHAB 1.8.3, configured with rfxcom:serialPort=/dev/ttyUSB0, and it works without problems.

With openHAB2.1 deb package, when manually adding (in paper ui) the RFXCOM USB Transceiver with /dev/ttyUSB0 (RFXCOM being the only installed addon, nothing else configured), openHAB immediately enters a restart loop without any log messages except for the restarts of the uis.

When I rmmod both usbseriel and ftdi_sio, the /dev/ttyUSB0 goes away, and when I manually add (in paper ui) RFXtrx433E with its serial, I have the same log messages as bricolo100.

**Comment by martinvw** [comment]
> except for the restarts of the uis.

Could you give a debug log for this, I do not understand what you mean with this?

What java version are you running this on?

I remember that there used to a param so supply which ports can be used by the jdk I do not know whether this is still a problem? Also the dial out used to be a problem but if it works in openHAB 1.8 then that should be okay, or you run them under a different user.

https://community.openhab.org/t/serial-binding-on-rpi/4199

**Comment by McNetic** [comment]
```
# java -version
java version "1.8.0_131"
Java(TM) SE Runtime Environment (build 1.8.0_131-b11)
Java HotSpot(TM) Client VM (build 25.131-b11, mixed mode)

```
I already have
```
EXTRA_JAVA_OPTS="-Dgnu.io.rxtx.SerialPorts=/dev/ttyUSB0"
```
openhab user is in dialout group, I also tried ``` rfxcom:serialPort=/dev/ttyUSB0 ``` in openhab.cfg as well as manually adding the Bridge in a .things file, with the same result: As soon as the thing is added, openHAB enters a restart loop. You can see this in the following log:
I started an empty install of openHAB. I did nothing for some time, so no log messages. As soon as I clicked "Add" in paper ui, the rfxcom discovery started (and failed with trace log, as expected). Then I manually added the RFXCom USB Transceiver, and as soon as that was done, the ui became unresponsive, and the restart loop begins. The restart normally happens as soon as paper ui is finished loading, so sometimes you can load it in browser, sometimes not even that.
```
2017-06-30 13:12:04.361 [INFO ] [.dashboard.internal.DashboardService] - Started dashboard at http://10.36.36.3:8080
2017-06-30 13:12:04.419 [INFO ] [.dashboard.internal.DashboardService] - Started dashboard at https://10.36.36.3:8443
2017-06-30 13:13:05.966 [INFO ] [basic.internal.servlet.WebAppServlet] - Started Basic UI at /basicui/app
2017-06-30 13:13:07.410 [INFO ] [assic.internal.servlet.WebAppServlet] - Started Classic UI at /classicui/app
2017-06-30 13:13:09.105 [INFO ] [arthome.ui.paper.internal.PaperUIApp] - Started Paper UI at /paperui
2017-06-30 13:13:10.476 [INFO ] [ui.habmin.internal.servlet.HABminApp] - Started HABmin servlet at /habmin
2017-06-30 13:13:11.275 [INFO ] [panel.internal.HABPanelDashboardTile] - Started HABPanel at /habpanel
2017-06-30 15:41:03.515 [ERROR] [rnal.discovery.RFXComBridgeDiscovery] - Error occurred during discovery
java.io.IOException: device not found (2)
        at jd2xx.JD2XX.listDevices(Native Method)
        at jd2xx.JD2XX.listDevicesByDescription(JD2XX.java:826)
        at org.openhab.binding.rfxcom.internal.discovery.RFXComBridgeDiscovery.discoverRfxcom(RFXComBridgeDiscovery.java:89)
        at org.openhab.binding.rfxcom.internal.discovery.RFXComBridgeDiscovery.startScan(RFXComBridgeDiscovery.java:66)
        at org.eclipse.smarthome.config.discovery.AbstractDiscoveryService.startScan(AbstractDiscoveryService.java:199)
        at org.eclipse.smarthome.config.discovery.internal.DiscoveryServiceRegistryImpl.startScan(DiscoveryServiceRegistryImpl.java:392)
        at org.eclipse.smarthome.config.discovery.internal.DiscoveryServiceRegistryImpl.startScans(DiscoveryServiceRegistryImpl.java:377)
        at org.eclipse.smarthome.config.discovery.internal.DiscoveryServiceRegistryImpl.startScan(DiscoveryServiceRegistryImpl.java:221)
        at org.eclipse.smarthome.io.rest.core.discovery.DiscoveryResource.scan(DiscoveryResource.java:86)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)[:1.8.0_131]
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)[:1.8.0_131]
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)[:1.8.0_131]
        at java.lang.reflect.Method.invoke(Method.java:498)[:1.8.0_131]
        at org.glassfish.jersey.server.model.internal.ResourceMethodInvocationHandlerFactory$1.invoke(ResourceMethodInvocationHandlerFactory.java:81)[158:org.glassfish.jersey.core.jersey-server:2.22.2]
        at org.glassfish.jersey.server.model.internal.AbstractJavaResourceMethodDispatcher$1.run(AbstractJavaResourceMethodDispatcher.java:144)[158:org.glassfish.jersey.core.jersey-server:2.22.2]
        at org.glassfish.jersey.server.model.internal.AbstractJavaResourceMethodDispatcher.invoke(AbstractJavaResourceMethodDispatcher.java:161)[158:org.glassfish.jersey.core.jersey-server:2.22.2]
        at org.glassfish.jersey.server.model.internal.JavaResourceMethodDispatcherProvider$ResponseOutInvoker.doDispatch(JavaResourceMethodDispatcherProvider.java:160)[158:org.glassfish.jersey.core.jersey-server:2.22.2]
        at org.glassfish.jersey.server.model.internal.AbstractJavaResourceMethodDispatcher.dispatch(AbstractJavaResourceMethodDispatcher.java:99)[158:org.glassfish.jersey.core.jersey-server:2.22.2]
        at org.glassfish.jersey.server.model.ResourceMethodInvoker.invoke(ResourceMethodInvoker.java:389)[158:org.glassfish.jersey.core.jersey-server:2.22.2]
        at org.glassfish.jersey.server.model.ResourceMethodInvoker.apply(ResourceMethodInvoker.java:347)[158:org.glassfish.jersey.core.jersey-server:2.22.2]
        at org.glassfish.jersey.server.model.ResourceMethodInvoker.apply(ResourceMethodInvoker.java:102)[158:org.glassfish.jersey.core.jersey-server:2.22.2]
        at org.glassfish.jersey.server.ServerRuntime$2.run(ServerRuntime.java:326)[158:org.glassfish.jersey.core.jersey-server:2.22.2]
        at org.glassfish.jersey.internal.Errors$1.call(Errors.java:271)[157:org.glassfish.jersey.core.jersey-common:2.22.2]
        at org.glassfish.jersey.internal.Errors$1.call(Errors.java:267)[157:org.glassfish.jersey.core.jersey-common:2.22.2]
        at org.glassfish.jersey.internal.Errors.process(Errors.java:315)[157:org.glassfish.jersey.core.jersey-common:2.22.2]
        at org.glassfish.jersey.internal.Errors.process(Errors.java:297)[157:org.glassfish.jersey.core.jersey-common:2.22.2]
        at org.glassfish.jersey.internal.Errors.process(Errors.java:267)[157:org.glassfish.jersey.core.jersey-common:2.22.2]
        at org.glassfish.jersey.process.internal.RequestScope.runInScope(RequestScope.java:317)[157:org.glassfish.jersey.core.jersey-common:2.22.2]
        at org.glassfish.jersey.server.ServerRuntime.process(ServerRuntime.java:305)[158:org.glassfish.jersey.core.jersey-server:2.22.2]
        at org.glassfish.jersey.server.ApplicationHandler.handle(ApplicationHandler.java:1154)[158:org.glassfish.jersey.core.jersey-server:2.22.2]
        at org.glassfish.jersey.servlet.WebComponent.serviceImpl(WebComponent.java:473)[155:org.glassfish.jersey.containers.jersey-container-servlet-core:2.22.2]
        at org.glassfish.jersey.servlet.WebComponent.service(WebComponent.java:427)[155:org.glassfish.jersey.containers.jersey-container-servlet-core:2.22.2]
        at org.glassfish.jersey.servlet.ServletContainer.service(ServletContainer.java:388)[155:org.glassfish.jersey.containers.jersey-container-servlet-core:2.22.2]
        at org.glassfish.jersey.servlet.ServletContainer.service(ServletContainer.java:341)[155:org.glassfish.jersey.containers.jersey-container-servlet-core:2.22.2]
        at org.glassfish.jersey.servlet.ServletContainer.service(ServletContainer.java:228)[155:org.glassfish.jersey.containers.jersey-container-servlet-core:2.22.2]
        at com.eclipsesource.jaxrs.publisher.internal.ServletContainerBridge.service(ServletContainerBridge.java:76)[9:com.eclipsesource.jaxrs.publisher:5.3.1.201602281253]
        at org.eclipse.jetty.servlet.ServletHolder.handle(ServletHolder.java:812)[81:org.eclipse.jetty.servlet:9.2.19.v20160908]
        at org.eclipse.jetty.servlet.ServletHandler.doHandle(ServletHandler.java:587)[81:org.eclipse.jetty.servlet:9.2.19.v20160908]
        at org.ops4j.pax.web.service.jetty.internal.HttpServiceServletHandler.doHandle(HttpServiceServletHandler.java:71)[172:org.ops4j.pax.web.pax-web-jetty:4.3.0]
        at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:143)[80:org.eclipse.jetty.server:9.2.19.v20160908]
        at org.eclipse.jetty.security.SecurityHandler.handle(SecurityHandler.java:577)[79:org.eclipse.jetty.security:9.2.19.v20160908]
        at org.eclipse.jetty.server.session.SessionHandler.doHandle(SessionHandler.java:223)[80:org.eclipse.jetty.server:9.2.19.v20160908]
        at org.eclipse.jetty.server.handler.ContextHandler.doHandle(ContextHandler.java:1127)[80:org.eclipse.jetty.server:9.2.19.v20160908]
        at org.ops4j.pax.web.service.jetty.internal.HttpServiceContext.doHandle(HttpServiceContext.java:287)[172:org.ops4j.pax.web.pax-web-jetty:4.3.0]
        at org.eclipse.jetty.servlet.ServletHandler.doScope(ServletHandler.java:515)[81:org.eclipse.jetty.servlet:9.2.19.v20160908]
        at org.eclipse.jetty.server.session.SessionHandler.doScope(SessionHandler.java:185)[80:org.eclipse.jetty.server:9.2.19.v20160908]
        at org.eclipse.jetty.server.handler.ContextHandler.doScope(ContextHandler.java:1061)[80:org.eclipse.jetty.server:9.2.19.v20160908]
        at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:141)[80:org.eclipse.jetty.server:9.2.19.v20160908]
        at org.ops4j.pax.web.service.jetty.internal.JettyServerHandlerCollection.handle(JettyServerHandlerCollection.java:80)[172:org.ops4j.pax.web.pax-web-jetty:4.3.0]
        at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:97)[80:org.eclipse.jetty.server:9.2.19.v20160908]
        at org.eclipse.jetty.server.Server.handle(Server.java:499)[80:org.eclipse.jetty.server:9.2.19.v20160908]
        at org.eclipse.jetty.server.HttpChannel.handle(HttpChannel.java:311)[80:org.eclipse.jetty.server:9.2.19.v20160908]
        at org.eclipse.jetty.server.HttpConnection.onFillable(HttpConnection.java:257)[80:org.eclipse.jetty.server:9.2.19.v20160908]
        at org.eclipse.jetty.io.AbstractConnection$2.run(AbstractConnection.java:544)[71:org.eclipse.jetty.io:9.2.19.v20160908]
        at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:635)[83:org.eclipse.jetty.util:9.2.19.v20160908]
        at org.eclipse.jetty.util.thread.QueuedThreadPool$3.run(QueuedThreadPool.java:555)[83:org.eclipse.jetty.util:9.2.19.v20160908]
        at java.lang.Thread.run(Thread.java:748)[:1.8.0_131]
2017-06-30 15:42:18.189 [INFO ] [.dashboard.internal.DashboardService] - Started dashboard at http://10.36.36.3:8080
2017-06-30 15:42:18.250 [INFO ] [.dashboard.internal.DashboardService] - Started dashboard at https://10.36.36.3:8443
2017-06-30 15:43:18.320 [INFO ] [basic.internal.servlet.WebAppServlet] - Started Basic UI at /basicui/app
2017-06-30 15:43:20.002 [INFO ] [assic.internal.servlet.WebAppServlet] - Started Classic UI at /classicui/app
2017-06-30 15:43:21.662 [INFO ] [arthome.ui.paper.internal.PaperUIApp] - Started Paper UI at /paperui
2017-06-30 15:43:22.935 [INFO ] [ui.habmin.internal.servlet.HABminApp] - Started HABmin servlet at /habmin
2017-06-30 15:43:23.627 [INFO ] [panel.internal.HABPanelDashboardTile] - Started HABPanel at /habpanel
2017-06-30 15:44:18.274 [INFO ] [.dashboard.internal.DashboardService] - Started dashboard at http://10.36.36.3:8080
2017-06-30 15:44:18.370 [INFO ] [.dashboard.internal.DashboardService] - Started dashboard at https://10.36.36.3:8443
2017-06-30 15:45:19.065 [INFO ] [basic.internal.servlet.WebAppServlet] - Started Basic UI at /basicui/app
2017-06-30 15:45:20.607 [INFO ] [assic.internal.servlet.WebAppServlet] - Started Classic UI at /classicui/app
2017-06-30 15:45:22.200 [INFO ] [arthome.ui.paper.internal.PaperUIApp] - Started Paper UI at /paperui
2017-06-30 15:45:23.531 [INFO ] [ui.habmin.internal.servlet.HABminApp] - Started HABmin servlet at /habmin
2017-06-30 15:45:24.286 [INFO ] [panel.internal.HABPanelDashboardTile] - Started HABPanel at /habpanel
2017-06-30 15:46:18.158 [INFO ] [.dashboard.internal.DashboardService] - Started dashboard at http://10.36.36.3:8080
2017-06-30 15:46:18.211 [INFO ] [.dashboard.internal.DashboardService] - Started dashboard at https://10.36.36.3:8443
2017-06-30 15:47:19.668 [INFO ] [basic.internal.servlet.WebAppServlet] - Started Basic UI at /basicui/app
2017-06-30 15:47:21.049 [INFO ] [assic.internal.servlet.WebAppServlet] - Started Classic UI at /classicui/app
2017-06-30 15:47:22.809 [INFO ] [arthome.ui.paper.internal.PaperUIApp] - Started Paper UI at /paperui
2017-06-30 15:47:24.004 [INFO ] [ui.habmin.internal.servlet.HABminApp] - Started HABmin servlet at /habmin
2017-06-30 15:47:24.719 [INFO ] [panel.internal.HABPanelDashboardTile] - Started HABPanel at /habpanel
2017-06-30 15:48:19.575 [INFO ] [.dashboard.internal.DashboardService] - Started dashboard at http://10.36.36.3:8080
2017-06-30 15:48:19.643 [INFO ] [.dashboard.internal.DashboardService] - Started dashboard at https://10.36.36.3:8443

```

**Comment by martinvw** [comment]
And this does not happen without the RFXCOM module, that is nasty indeed.

And this only happens as soon as the 'RFXCOM USB Transceiver' has been added?

Could you enable debug information? Maybe if you start it manually up to karaf you might be able to influence something there.

**Comment by McNetic** [comment]
Yes, it happens once I add the RFXCOM USB Transceiver. It goes away as soon as I manage to remove it again. I enabled TRACE log for binding.rfxcom. That's one restart cycle:
```
2017-06-30 23:39:40.922 [INFO ] [.dashboard.internal.DashboardService] - Started dashboard at http://10.36.36.3:8080
2017-06-30 23:39:40.980 [INFO ] [.dashboard.internal.DashboardService] - Started dashboard at https://10.36.36.3:8443
2017-06-30 23:40:41.730 [INFO ] [basic.internal.servlet.WebAppServlet] - Started Basic UI at /basicui/app
2017-06-30 23:40:43.305 [INFO ] [assic.internal.servlet.WebAppServlet] - Started Classic UI at /classicui/app
2017-06-30 23:40:45.380 [INFO ] [arthome.ui.paper.internal.PaperUIApp] - Started Paper UI at /paperui
2017-06-30 23:40:46.867 [INFO ] [ui.habmin.internal.servlet.HABminApp] - Started HABmin servlet at /habmin
2017-06-30 23:40:47.559 [INFO ] [panel.internal.HABPanelDashboardTile] - Started HABPanel at /habpanel
2017-06-30 23:40:47.816 [DEBUG] [org.openhab.binding.rfxcom          ] - BundleEvent STARTING - org.openhab.binding.rfxcom
2017-06-30 23:40:47.828 [DEBUG] [org.openhab.binding.rfxcom          ] - BundleEvent STARTED - org.openhab.binding.rfxcom
2017-06-30 23:40:47.911 [DEBUG] [org.openhab.binding.rfxcom          ] - ServiceEvent REGISTERED - {org.eclipse.smarthome.config.discovery.DiscoveryService}={component.name=org.openhab.binding.rfxcom.discovery, component.id=203, service.id=328, service.bundleid=208, service.scope=bundle} - org.openhab.binding.rfxcom
2017-06-30 23:40:48.154 [DEBUG] [org.openhab.binding.rfxcom          ] - ServiceEvent REGISTERED - {org.eclipse.smarthome.core.thing.binding.ThingHandlerFactory}={component.name=org.openhab.binding.rfxcom.internal.RFXComHandlerFactory, component.id=204, service.id=329, service.bundleid=208, service.scope=bundle} - org.openhab.binding.rfxcom
2017-06-30 23:40:51.633 [DEBUG] [org.openhab.binding.rfxcom          ] - ServiceEvent REGISTERED - {org.eclipse.smarthome.config.discovery.DiscoveryService}={service.id=332, service.bundleid=208, service.scope=singleton} - org.openhab.binding.rfxcom
2017-06-30 23:40:51.857 [DEBUG] [g.rfxcom.handler.RFXComBridgeHandler] - Initializing RFXCOM bridge handler
2017-06-30 23:40:52.123 [DEBUG] [g.rfxcom.handler.RFXComBridgeHandler] - Checking RFXCOM transceiver connection, thing status = OFFLINE
2017-06-30 23:40:52.134 [DEBUG] [g.rfxcom.handler.RFXComBridgeHandler] - Connecting to RFXCOM transceiver
2017-06-30 23:40:52.209 [DEBUG] [rnal.connector.RFXComSerialConnector] - Disconnecting
2017-06-30 23:40:52.228 [DEBUG] [rnal.connector.RFXComSerialConnector] - Closed
2017-06-30 23:41:41.658 [INFO ] [.dashboard.internal.DashboardService] - Started dashboard at http://10.36.36.3:8080
2017-06-30 23:41:41.740 [INFO ] [.dashboard.internal.DashboardService] - Started dashboard at https://10.36.36.3:8443
```
I don't get what you mean in your last paragraph. I did not disable any modules. I just do the following:
1) apt-get remove --purge openhab2 to get a clean start
2) apt-get install openhab2
3) add openhab user to dialup group
4) service openhab2 start
5) In ui, select Standard Setup
6) In paper ui, install rfxcom addon
7) In paper ui, manually add rfxcom usb transceiver

The device has 512 MB memory, and shortly before the loop restart, its down to:
```
# free -h
             total       used       free     shared    buffers     cached
Mem:          497M       427M        69M         0B       9.5M       228M
-/+ buffers/cache:       189M       307M
Swap:           0B         0B         0B
```

How do I start to karaf?

**Comment by martinvw** [comment]
> How do I start to karaf?

if instead of 

`service openhab2 start` you navigate to the openHAB directory and call `./start.sh` 

Looking at the code it somehow seems to connect, disconnect and reconnect but it fails in between the last two steps.

I think the 69M might be suspicious you could try to add a swap partition.

**Comment by McNetic** [comment]
Ok, I think I found the problem. When starting start.sh, after about a minute:
```
/usr/bin/java: symbol lookup error: /var/lib/openhab2/tmp/libNRJavaSerial_HF_root_0/libNRJavaSerial_HF.so: undefined symbol: __fdelt_chk
```
The system is still on debian 7 wheezy, with libc 2.13. According to some sources, libNRJavaSerial requires at least libc 2.16. Still, this error should somehow be caught and shown to the user if possible. Maybe openhab2 debian image should also depend on libc 2.16....

Unfortunately, I can not easily upgrade the beaglebone to a more current debian version atm.

**Comment by martinvw** [comment]
Aha, see also:

https://community.openhab.org/t/banana-pi-with-z-stick-aeotec-lab-dev-ttyusb0-does-not-exist/26473
https://github.com/openhab/openhab-core/issues/111

However the issue more or less suggests that it should have been resolved, so that is disturbing.

**Comment by conditio** [comment]
It's not resolved, not for me running CentOs 6.5 at least...

**Comment by McNetic** [comment]
As said, at least libc 2.16 is required for this to work. You'll have to update the system...

**Comment by conditio** [comment]
That's not whats beeing said here: https://github.com/cvanorman/nrjavaserial/issues/4

And here:

https://github.com/openhab/openhab-core/issues/111#issuecomment-278581282

Whats beeing said if you read around is that many users are stil stuck with lower glibc and theres been a couple of attempts lowering required version...

I have many other bindings running in centos 6.5 without problems. And some users seem to have even the libnrjavaserial running with lower glibc than 2.16!? But i guess that it needs to be compiled for those specific architectures x86/64 arm etc...
