### ISSUE TITLE
[Netatmo] Not able to get values

### ISSUE THREAD

**Issue by mcarlosro** [openhab/openhab2-addons#1655]
I have the following error in the openhab.log:
2017-01-03 23:08:11.947 [ERROR] [netatmo.handler.NetatmoDeviceHandler] - Exception when trying to update channels: null

and of course, I have no values (NULL in the sitemap).

This is a clean install and API and 2 thermostat are ONLINE.

**Comment by Homey-GER** [comment]
Works fine for me, can you give some more details about your configuration, items, sitemap etc.

Also what Devices you are talking about? Netatmo has lots of them! Weather Stations, Thermostats etc.

**Comment by mcarlosro** [comment]
A clean installation from the snapshot con Jan 3rd.
I used these steps from HABmin

1. Add netstatmo binding
2. Add a netatmo API and configure it.
3. Autodiscover things. 2 thermostat are discoverd.
4. Added both. No items were created.
5. Added a few items such as current temperature. 

NULL value is set for all of them.

**Comment by OliFu** [comment]
I have the same Problem.
Main station works fine. Outdoor module and additional indoor module doesn't work.
I have tried both to config the items: config with text file and also to config with the paper ui. Same result.
LOG: "Exception when trying to update channels: null"

**Comment by mcarlosro** [comment]
Any feedback on this? I can try to help in debugging if needed.

**Comment by githubhohdorfnet** [comment]
I have exactly the same problem as mcarlosro...

**Comment by larslak** [comment]
tested with 2.0.0-SNAPSHOT Build #723 and seems to work now (had the same issue before that only the main module was working)

**Comment by mcarlosro** [comment]
Tested what suggested by @larslak and it is solved, although I needed to restart in order to get the values.

**Comment by SR-G** [comment]
I still have the same issue with OpenHAB 2.2.0-SNAPSHOT build #1044 (docker image).

`2017-10-14 11:45:37.308 [ERROR] [netatmo.handler.NetatmoDeviceHandler] - Exception when trying to update channels: null`

**Comment by njogu01** [comment]
the same problem ...
