### ISSUE TITLE
[Freebox] Not working since firmware v3.5

### ISSUE THREAD

**Issue by Orfait** [openhab/openhab2-addons#3198]
Hi,

Since the firmware v3.5 is installed on the Freebox, the binding has stopped working.

> 08:49:55.191 [ERROR] [inding.freebox.handler.FreeboxHandler] - Server state job - FreeboxException: org.codehaus.jackson.map.exc.UnrecognizedPropertyException: Unrecognized field "interface" (Class org.matmaul.freeboxos.lan.LanHostConfig), not marked as ignorable

## Environment
* Openhab 2.2.0 Release build
* Openhabian on Raspberry pi 3

**Comment by lolodomo** [comment]
I am still in version 3.4.1.
I will investigate when I have time.

**Comment by lolodomo** [comment]
I have now updated to firmware 3.5.1 and I can see the problem.
They moved API from 4.0 to 5.0 without updating the documentation !
I am trying to fix that.

**Comment by lolodomo** [comment]
It is fixed.

**Comment by VinceICPO** [comment]
Fantastic Lolodom, how do we fix it on our own OpenHAB servers?
I tried openHAB configuration tool + update... and reboot
but still have the issue thx

**Comment by lolodomo** [comment]
Sorry I can't help you, I always and only update with a manual installation of OH snapshot.
The fix should be available in the next OH snapshot.

**Comment by VinceICPO** [comment]
Ok, merci Laurent

**Comment by lolodomo** [comment]
I can confirm that the fix is available in openHAB snapshot 1212.
