### ISSUE TITLE
Zwave MT02646 Devolo Home Control Metering Plug.   Comm Error

### ISSUE THREAD

**Issue by shorty707** [openhab/openhab2-addons#796]
The Devolo Metering Power Switch
http://www.cd-jackson.com/index.php/zwave/zwave-device-database/zwave-device-list/devicesummary/1

Can be included and is correct discovered with all channels.

However there is no communication at all with this device.

This is the only Device where this happens for me and I think the comm error is related to the binding.

**Comment by cdjackson** [comment]
What does “Comm Error” mean? I don’t know this error so I’m not sure where it’s coming from?

**Comment by shorty707** [comment]
I included this node now multiple times.
I can be included.
It does serialize an XML.
I actually says in the log that it switches. But it is doing nothing. I tried it with another zwave controller (devolo itself; it worked there; so the device is not defect)

I can provide the Full Debug Log of the Inclusion and everything of that Node39 aswell

```
2016-04-15 19:57:43.320 [DEBUG] [ding.zwave.handler.ZWaveThingHandler] - NODE 39: Command received zwave:device:15348538564:node39:switch_binary --> OFF
2016-04-15 19:57:43.321 [DEBUG] [dclass.ZWaveBinarySwitchCommandClass] - NODE 39: Creating new message for application command SWITCH_BINARY_SET
2016-04-15 19:57:43.322 [DEBUG] [ve.internal.protocol.ZWaveController] - Message queued. Queue length = 1. Queue={}
2016-04-15 19:57:43.322 [DEBUG] [ocol.ZWaveController$ZWaveSendThread] - Took message from queue for sending. Queue length = 0
2016-04-15 19:57:43.323 [DEBUG] [wave.internal.protocol.SerialMessage] - Assembled message buffer = 01 0A 00 13 27 03 25 01 00 25 59 9A 
2016-04-15 19:57:43.324 [DEBUG] [ing.zwave.handler.ZWaveSerialHandler] - NODE 39: Sending REQUEST Message = 01 0A 00 13 27 03 25 01 00 25 59 9A 
2016-04-15 19:57:43.338 [DEBUG] [WaveSerialHandler$ZWaveReceiveThread] - Receive Message = 01 04 01 13 01 E8 
2016-04-15 19:57:43.340 [DEBUG] [ve.internal.protocol.ZWaveController] - Receive queue TAKE: Length=0
2016-04-15 19:57:43.341 [DEBUG] [wave.internal.protocol.SerialMessage] - Assembled message buffer = 01 04 01 13 01 E8 
2016-04-15 19:57:43.341 [DEBUG] [ve.internal.protocol.ZWaveController] - Process Message = 01 04 01 13 01 E8 
2016-04-15 19:57:43.342 [DEBUG] [ve.internal.protocol.ZWaveController] - Message: class=SendData[0x13], type=Response[0x01], priority=High, dest=255, callback=0, payload=01 
2016-04-15 19:57:43.343 [DEBUG] [l.serialmessage.SendDataMessageClass] - NODE 39: Sent Data successfully placed on stack.
2016-04-15 19:57:43.357 [DEBUG] [WaveSerialHandler$ZWaveReceiveThread] - Receive Message = 01 07 00 13 59 00 00 03 B1 
2016-04-15 19:57:43.360 [DEBUG] [ve.internal.protocol.ZWaveController] - Receive queue TAKE: Length=0
2016-04-15 19:57:43.363 [DEBUG] [wave.internal.protocol.SerialMessage] - Assembled message buffer = 01 09 00 13 59 00 00 03 00 00 BF 
2016-04-15 19:57:43.364 [DEBUG] [ve.internal.protocol.ZWaveController] - Process Message = 01 09 00 13 59 00 00 03 00 00 BF 
2016-04-15 19:57:43.366 [DEBUG] [ve.internal.protocol.ZWaveController] - Message: class=SendData[0x13], type=Request[0x00], priority=High, dest=255, callback=0, payload=59 00 00 03 
2016-04-15 19:57:43.367 [DEBUG] [l.serialmessage.SendDataMessageClass] - NODE 39: SendData Request. CallBack ID = 89, Status = Transmission complete and ACK received(0)
2016-04-15 19:57:43.369 [DEBUG] [.serialmessage.ZWaveCommandProcessor] - Checking transaction complete: Sent Message: class=SendData[0x13], type=Request[0x00], priority=Set, dest=39, callback=89, payload=27 03 25 01 00 
2016-04-15 19:57:43.371 [DEBUG] [.serialmessage.ZWaveCommandProcessor] - Checking transaction complete: Recv Message: class=SendData[0x13], type=Request[0x00], priority=High, dest=255, callback=0, payload=59 00 00 03 
2016-04-15 19:57:43.372 [DEBUG] [.serialmessage.ZWaveCommandProcessor] - Checking transaction complete: class=SendData, callback id=89, expected=SendData, cancelled=false        transaction complete!
2016-04-15 19:57:43.373 [DEBUG] [ve.internal.protocol.ZWaveController] - Notifying event listeners: ZWaveTransactionCompletedEvent
2016-04-15 19:57:43.374 [DEBUG] [ocol.ZWaveController$ZWaveSendThread] - NODE 39: Response processed after 49ms/4472ms.
2016-04-15 19:57:43.543 [INFO ] [marthome.event.ItemStateChangedEvent] - zwave_device_15348538564_node39_switch_binary changed from ON to OFF
2016-04-15 19:57:44.771 [DEBUG] [WaveSerialHandler$ZWaveReceiveThread] - Receive Message = 01 0E 00 04 00 12 08 8F 01 01 04 30 03 00 0C 5B 
2016-04-15 19:57:44.774 [DEBUG] [ve.internal.protocol.ZWaveController] - Receive queue TAKE: Length=0
2016-04-15 19:57:44.775 [DEBUG] [wave.internal.protocol.SerialMessage] - Assembled message buffer = 01 0E 00 04 00 12 08 8F 01 01 04 30 03 00 0C 5B 
2016-04-15 19:57:44.777 [DEBUG] [ve.internal.protocol.ZWaveController] - Process Message = 01 0E 00 04 00 12 08 8F 01 01 04 30 03 00 0C 5B 
2016-04-15 19:57:44.779 [DEBUG] [ve.internal.protocol.ZWaveController] - Message: class=ApplicationCommandHandler[0x04], type=Request[0x00], priority=High, dest=255, callback=0, payload=00 12 08 8F 01 01 04 30 03 00 0C 

```

**Comment by shorty707** [comment]
using the "physcial" button on the power switch turns on / off the switch
but there in NOTHING in the log when using the physical button

**Comment by cdjackson** [comment]
If there's nothing in the log then check the association is set correctly. It's hard to expect the binding to know the device has changed unless the device sends a notification ;)

**Comment by shorty707** [comment]
and vice versa? (one comment above)

**Comment by shorty707** [comment]
I assume there is an error on inclusion ....  wrong manufacturer Id serialized to xml?
when I try to upload the auto generated XML to the DB it says

--> Manufacturer 7FFFFFFF is not known! Please update the manufacturer database and try again.

XML:

<node>
  <deviceClass>
    <basicDeviceClass>ROUTING_SLAVE</basicDeviceClass>
    <genericDeviceClass>BINARY_SWITCH</genericDeviceClass>
    <specificDeviceClass>POWER_SWITCH_BINARY</specificDeviceClass>
  </deviceClass>
  <homeId>0xca92feee</homeId>
  <nodeId>39</nodeId>
  <version>4</version>
  <manufacturer>0x7fffffff</manufacturer>
  <deviceId>0x7fffffff</deviceId>
  <deviceType>0x7fffffff</deviceType>
  <listening>true</listening>
  <frequentlyListening>false</frequentlyListening>
  <routing>true</routing>
  <security>false</security>
  <beaming>true</beaming>
  <maxBaudRate>40000</maxBaudRate>
  <supportedCommandClasses>
    <entry>
      <commandClass>NO_OPERATION</commandClass>
      <noOperationCommandClass>
        <version>1</version>
        <instances>1</instances>
      </noOperationCommandClass>
    </entry>
    <entry>
      <commandClass>SWITCH_BINARY</commandClass>
      <binarySwitchCommandClass>
        <version>1</version>
        <instances>1</instances>
        <isGetSupported>true</isGetSupported>
      </binarySwitchCommandClass>
    </entry>
    <entry>
      <commandClass>BASIC</commandClass>
      <basicCommandClass>
        <version>1</version>
        <instances>1</instances>
        <isGetSupported>true</isGetSupported>
      </basicCommandClass>
    </entry>
  </supportedCommandClasses>
  <securedCommandClasses/>
  <nodeNeighbors>
    <int>1</int>
    <int>9</int>
    <int>12</int>
    <int>24</int>
  </nodeNeighbors>
  <lastSent>2016-04-15 18:24:11.585 UTC</lastSent>
  <lastReceived>2016-04-15 18:24:11.731 UTC</lastReceived>
</node>

**Comment by xsnrg** [comment]
I would agree with the error on inclusion.  I get the 7FFFFFFF message when a device is gone or powered down if I have not removed it properly from the controller (sometimes I couldn't).  Try un-including it first, and then include it again.  It will get a new ID number, but hopefully bind correctly.

**Comment by shorty707** [comment]
for that device I did run exlusion properly ( was also confirmed and log and thing was removed automatically). anyways that 7FFFFFFF comes specifically for that device every time

**Comment by cdjackson** [comment]
Associations won't impact the commanding. The command, from the log you presented, looks fine and is acked by the device. So, from what I can tell, it looks like it's working as far as the protocol goes

> I assume there is an error on inclusion

Why? Either the device is included, or not. As far as I can tell, given it's in the network, I guess inclusion worked. The fact that you see the 7FFFFFFF shouldn't be anything to do with inclusion - I suspect it's because this device isn't supporting the provision of manufacture information! (or at least it says it doesn't support it).

Please can you provide a debug log of the initialisation - just delete the XML file, and restart the binding and provide the log.

**Comment by shorty707** [comment]
[node39_restartbind.txt](https://github.com/openhab/openhab2-addons/files/221676/node39_restartbind.txt)

**Comment by cdjackson** [comment]
Following this log, is it still showing a manufacturer etc of 7FFFFFFF?

**Comment by shorty707** [comment]
first... the device still does not work... although the log says the binary switch command on was sent and the item changed to ON ... the physcial device shows no reaction

second... no the manf. id changed: manufacturer>0x175</manufacturer

third:
updating the db with the xml now shows:
Warning: Device being updated already contains the reference "0001:0011"!
Error: The firmware version for this device is not know. Processing of the XML halted.

**Comment by cdjackson** [comment]
It looks fine except the device doesn’t seem to respond to the GET requests. This is causing it to timeout. I’ll update the database to fix this.

I’m not sure this will fix everything since as I said before, the binding seems to be sending the command, and the device seems to ack this request already.

The database is stopping you loading the XML again - this is right (why do you want to load it again?).

**Comment by cdjackson** [comment]
Please can you let me know what node 9 is - it also has an issue it seems.

**Comment by shorty707** [comment]
Aeon ZW100 Multi Sensor
http://www.cd-jackson.com/index.php/zwave/zwave-device-database/zwave-device-list/devicesummary/73

**Comment by cdjackson** [comment]
I suspect parameter 100 is write only - it’s not responding to a GET on parameter 100.  I’ll update this.

**Comment by shorty707** [comment]
cool :)

If you want more problems ;)  here is a device (NODE36) that is not in the DB yet.... however its not generating the XML and therefore I cannot upload as a new device to the DB. (I did wake up very often and waited days).... maybe log tells you something:

```
2016-04-15 22:18:59.971 [DEBUG] [WaveSerialHandler$ZWaveReceiveThread] - Receive Message = 01 1E 00 49 84 24 18 04 12 02 5E 70 85 2D 8E 80 84 8F 5A 59 5B 73 86 72 EF 20 5B 26 27 2B 60 86 
2016-04-15 22:18:59.974 [DEBUG] [ve.internal.protocol.ZWaveController] - Receive queue TAKE: Length=0
2016-04-15 22:18:59.976 [DEBUG] [wave.internal.protocol.SerialMessage] - Assembled message buffer = 01 1E 00 49 84 24 18 04 12 02 5E 70 85 2D 8E 80 84 8F 5A 59 5B 73 86 72 EF 20 5B 26 27 2B 60 86 
2016-04-15 22:18:59.978 [DEBUG] [ve.internal.protocol.ZWaveController] - Process Message = 01 1E 00 49 84 24 18 04 12 02 5E 70 85 2D 8E 80 84 8F 5A 59 5B 73 86 72 EF 20 5B 26 27 2B 60 86 
2016-04-15 22:18:59.980 [DEBUG] [ve.internal.protocol.ZWaveController] - Message: class=ApplicationUpdate[0x49], type=Request[0x00], priority=High, dest=255, callback=0, payload=84 24 18 04 12 02 5E 70 85 2D 8E 80 84 8F 5A 59 5B 73 86 72 EF 20 5B 26 27 2B 60 
2016-04-15 22:18:59.981 [DEBUG] [essage.ApplicationUpdateMessageClass] - NODE 36: Application update request. Node information received.
2016-04-15 22:18:59.982 [DEBUG] [ng.zwave.internal.protocol.ZWaveNode] - NODE 36: Node is ALIVE. Init stage is PING:{}.
2016-04-15 22:18:59.982 [DEBUG] [ve.internal.protocol.ZWaveController] - Notifying event listeners: ZWaveNodeStatusEvent
2016-04-15 22:18:59.983 [DEBUG] [g.zwave.internal.ZWaveNetworkMonitor] - NODE 36: Node Status event - Node is ALIVE
2016-04-15 22:18:59.983 [DEBUG] [ding.zwave.handler.ZWaveThingHandler] - NODE 36: Got an event from Z-Wave network: ZWaveNodeStatusEvent
2016-04-15 22:18:59.984 [DEBUG] [ding.zwave.handler.ZWaveThingHandler] - NODE 36: Setting ONLINE
2016-04-15 22:18:59.986 [DEBUG] [nitialization.ZWaveNodeStageAdvancer] - NODE 36: Node Status event during initialisation - Node is ALIVE
2016-04-15 22:18:59.987 [DEBUG] [nitialization.ZWaveNodeStageAdvancer] - NODE 36: Node advancer - PING: queue length(0), free to send(true)
2016-04-15 22:18:59.987 [INFO ] [me.event.ThingStatusInfoChangedEvent] - 'zwave:device:15348538564:node36' changed from OFFLINE to ONLINE
2016-04-15 22:18:59.988 [DEBUG] [nitialization.ZWaveNodeStageAdvancer] - NODE 36: Node advancer: loop - PING try 1: stageAdvanced(false)
2016-04-15 22:18:59.989 [DEBUG] [nitialization.ZWaveNodeStageAdvancer] - NODE 36: Node advancer: PING - send NoOperation
2016-04-15 22:18:59.989 [DEBUG] [ndclass.ZWaveNoOperationCommandClass] - NODE 36: Creating new message for command No Operation
2016-04-15 22:18:59.990 [DEBUG] [nitialization.ZWaveNodeStageAdvancer] - NODE 36: Node advancer - queued packet. Queue length is 1
2016-04-15 22:18:59.991 [DEBUG] [ve.internal.protocol.ZWaveController] - Message queued. Queue length = 12. Queue={}
2016-04-15 22:18:59.991 [DEBUG] [ve.internal.protocol.ZWaveController] - NODE 36: Node Status event - Node is ALIVE
2016-04-15 22:18:59.992 [DEBUG] [tocol.commandclass.ZWaveCommandClass] - NODE 36: Creating new instance of command class ZWAVE_PLUS_INFO
2016-04-15 22:18:59.993 [DEBUG] [tocol.commandclass.ZWaveCommandClass] - NODE 36: Command class ZWAVE_PLUS_INFO, endpoint null created
2016-04-15 22:18:59.993 [DEBUG] [essage.ApplicationUpdateMessageClass] - NODE 36: Application update is adding command class ZWAVE_PLUS_INFO.
2016-04-15 22:18:59.994 [DEBUG] [ng.zwave.internal.protocol.ZWaveNode] - NODE 36: Adding command class ZWAVE_PLUS_INFO to the list of supported command classes.
2016-04-15 22:18:59.995 [DEBUG] [tocol.commandclass.ZWaveCommandClass] - NODE 36: Creating new instance of command class CONFIGURATION
2016-04-15 22:18:59.996 [DEBUG] [tocol.commandclass.ZWaveCommandClass] - NODE 36: Command class CONFIGURATION, endpoint null created
2016-04-15 22:18:59.996 [DEBUG] [essage.ApplicationUpdateMessageClass] - NODE 36: Application update is adding command class CONFIGURATION.
2016-04-15 22:18:59.997 [DEBUG] [ng.zwave.internal.protocol.ZWaveNode] - NODE 36: Adding command class CONFIGURATION to the list of supported command classes.
2016-04-15 22:18:59.998 [DEBUG] [tocol.commandclass.ZWaveCommandClass] - NODE 36: Creating new instance of command class ASSOCIATION
2016-04-15 22:18:59.998 [DEBUG] [tocol.commandclass.ZWaveCommandClass] - NODE 36: Command class ASSOCIATION, endpoint null created
2016-04-15 22:18:59.999 [DEBUG] [essage.ApplicationUpdateMessageClass] - NODE 36: Application update is adding command class ASSOCIATION.
2016-04-15 22:18:59.999 [DEBUG] [ng.zwave.internal.protocol.ZWaveNode] - NODE 36: Adding command class ASSOCIATION to the list of supported command classes.
2016-04-15 22:19:00.000 [WARN ] [tocol.commandclass.ZWaveCommandClass] - NODE 36: Unsupported command class SCENE_CONTROLLER_CONF
2016-04-15 22:19:00.001 [WARN ] [tocol.commandclass.ZWaveCommandClass] - NODE 36: Unsupported command class MULTI_INSTANCE_ASSOCIATION
2016-04-15 22:19:00.001 [DEBUG] [tocol.commandclass.ZWaveCommandClass] - NODE 36: Creating new instance of command class BATTERY
2016-04-15 22:19:00.002 [DEBUG] [tocol.commandclass.ZWaveCommandClass] - NODE 36: Command class BATTERY, endpoint null created
2016-04-15 22:19:00.003 [DEBUG] [essage.ApplicationUpdateMessageClass] - NODE 36: Application update is adding command class BATTERY.
2016-04-15 22:19:00.003 [DEBUG] [ng.zwave.internal.protocol.ZWaveNode] - NODE 36: Adding command class BATTERY to the list of supported command classes.
2016-04-15 22:19:00.004 [DEBUG] [tocol.commandclass.ZWaveCommandClass] - NODE 36: Creating new instance of command class WAKE_UP
2016-04-15 22:19:00.005 [DEBUG] [tocol.commandclass.ZWaveCommandClass] - NODE 36: Command class WAKE_UP, endpoint null created
2016-04-15 22:19:00.006 [DEBUG] [essage.ApplicationUpdateMessageClass] - NODE 36: Application update is adding command class WAKE_UP.
2016-04-15 22:19:00.007 [DEBUG] [ng.zwave.internal.protocol.ZWaveNode] - NODE 36: Adding command class WAKE_UP to the list of supported command classes.
2016-04-15 22:19:00.008 [DEBUG] [tocol.commandclass.ZWaveCommandClass] - NODE 36: Creating new instance of command class MULTI_CMD
2016-04-15 22:19:00.009 [DEBUG] [tocol.commandclass.ZWaveCommandClass] - NODE 36: Command class MULTI_CMD, endpoint null created
2016-04-15 22:19:00.009 [DEBUG] [essage.ApplicationUpdateMessageClass] - NODE 36: Application update is adding command class MULTI_CMD.
2016-04-15 22:19:00.010 [DEBUG] [ng.zwave.internal.protocol.ZWaveNode] - NODE 36: Adding command class MULTI_CMD to the list of supported command classes.
2016-04-15 22:19:00.011 [DEBUG] [tocol.commandclass.ZWaveCommandClass] - NODE 36: Creating new instance of command class DEVICE_RESET_LOCALLY
2016-04-15 22:19:00.011 [DEBUG] [tocol.commandclass.ZWaveCommandClass] - NODE 36: Command class DEVICE_RESET_LOCALLY, endpoint null created
2016-04-15 22:19:00.012 [DEBUG] [essage.ApplicationUpdateMessageClass] - NODE 36: Application update is adding command class DEVICE_RESET_LOCALLY.
2016-04-15 22:19:00.012 [DEBUG] [ng.zwave.internal.protocol.ZWaveNode] - NODE 36: Adding command class DEVICE_RESET_LOCALLY to the list of supported command classes.
2016-04-15 22:19:00.013 [WARN ] [tocol.commandclass.ZWaveCommandClass] - NODE 36: Unsupported command class ASSOCIATION_GROUP_INFO
2016-04-15 22:19:00.014 [DEBUG] [tocol.commandclass.ZWaveCommandClass] - NODE 36: Creating new instance of command class CENTRAL_SCENE
2016-04-15 22:19:00.015 [DEBUG] [tocol.commandclass.ZWaveCommandClass] - NODE 36: Command class CENTRAL_SCENE, endpoint null created
2016-04-15 22:19:00.016 [DEBUG] [essage.ApplicationUpdateMessageClass] - NODE 36: Application update is adding command class CENTRAL_SCENE.
2016-04-15 22:19:00.016 [DEBUG] [ng.zwave.internal.protocol.ZWaveNode] - NODE 36: Adding command class CENTRAL_SCENE to the list of supported command classes.
2016-04-15 22:19:00.017 [DEBUG] [tocol.commandclass.ZWaveCommandClass] - NODE 36: Creating new instance of command class POWERLEVEL
2016-04-15 22:19:00.018 [DEBUG] [tocol.commandclass.ZWaveCommandClass] - NODE 36: Command class POWERLEVEL, endpoint null created
2016-04-15 22:19:00.018 [DEBUG] [essage.ApplicationUpdateMessageClass] - NODE 36: Application update is adding command class POWERLEVEL.
2016-04-15 22:19:00.019 [DEBUG] [ng.zwave.internal.protocol.ZWaveNode] - NODE 36: Adding command class POWERLEVEL to the list of supported command classes.
2016-04-15 22:19:00.019 [DEBUG] [tocol.commandclass.ZWaveCommandClass] - NODE 36: Creating new instance of command class VERSION
2016-04-15 22:19:00.020 [DEBUG] [tocol.commandclass.ZWaveCommandClass] - NODE 36: Command class VERSION, endpoint null created
2016-04-15 22:19:00.021 [DEBUG] [essage.ApplicationUpdateMessageClass] - NODE 36: Application update is adding command class VERSION.
2016-04-15 22:19:00.021 [DEBUG] [ng.zwave.internal.protocol.ZWaveNode] - NODE 36: Adding command class VERSION to the list of supported command classes.
2016-04-15 22:19:00.022 [DEBUG] [tocol.commandclass.ZWaveCommandClass] - NODE 36: Creating new instance of command class MANUFACTURER_SPECIFIC
2016-04-15 22:19:00.022 [DEBUG] [tocol.commandclass.ZWaveCommandClass] - NODE 36: Command class MANUFACTURER_SPECIFIC, endpoint null created
2016-04-15 22:19:00.023 [DEBUG] [essage.ApplicationUpdateMessageClass] - NODE 36: Application update is adding command class MANUFACTURER_SPECIFIC.
2016-04-15 22:19:00.023 [DEBUG] [ng.zwave.internal.protocol.ZWaveNode] - NODE 36: Adding command class MANUFACTURER_SPECIFIC to the list of supported command classes.
2016-04-15 22:19:00.024 [DEBUG] [commandclass.ZWaveWakeUpCommandClass] - NODE 36: Is awake with 0 messages in the wake-up queue.
2016-04-15 22:19:00.025 [DEBUG] [ve.internal.protocol.ZWaveController] - Notifying event listeners: ZWaveWakeUpEvent
2016-04-15 22:19:00.025 [DEBUG] [ding.zwave.handler.ZWaveThingHandler] - NODE 36: Got an event from Z-Wave network: ZWaveWakeUpEvent
2016-04-15 22:19:00.026 [DEBUG] [nitialization.ZWaveNodeStageAdvancer] - NODE 36: Wakeup during initialisation.
2016-04-15 22:19:00.026 [DEBUG] [nitialization.ZWaveNodeStageAdvancer] - NODE 36: Node advancer - PING: queue length(1), free to send(false)
2016-04-15 22:19:00.027 [DEBUG] [nitialization.ZWaveNodeStageAdvancer] - NODE 36: Node advancer - queued packet. Queue length is 1
2016-04-15 22:19:00.028 [DEBUG] [ve.internal.protocol.ZWaveController] - Message queued. Queue length = 13. Queue={}
2016-04-15 22:19:00.029 [DEBUG] [.serialmessage.ZWaveCommandProcessor] - Checking transaction complete: Sent Message: class=SendData[0x13], type=Request[0x00], priority=Get, dest=39, callback=23, payload=27 02 25 02 
2016-04-15 22:19:00.031 [DEBUG] [.serialmessage.ZWaveCommandProcessor] - Checking transaction complete: Recv Message: class=ApplicationUpdate[0x49], type=Request[0x00], priority=High, dest=255, callback=0, payload=84 24 18 04 12 02 5E 70 85 2D 8E 80 84 8F 5A 59 5B 73 86 72 EF 20 5B 26 27 2B 60 
2016-04-15 22:19:00.032 [DEBUG] [.serialmessage.ZWaveCommandProcessor] - Checking transaction complete: class=ApplicationUpdate, callback id=23, expected=ApplicationCommandHandler, cancelled=false      MISMATCH
2016-04-15 22:19:01.029 [DEBUG] [commandclass.ZWaveWakeUpCommandClass] - NODE 36: No more messages, go back to sleep
2016-04-15 22:19:01.029 [DEBUG] [commandclass.ZWaveWakeUpCommandClass] - NODE 36: Creating new message for application command WAKE_UP_NO_MORE_INFORMATION
2016-04-15 22:19:01.035 [DEBUG] [ve.internal.protocol.ZWaveController] - Message queued. Queue length = 14. Queue={}
2016-04-15 22:19:03.029 [DEBUG] [nitialization.ZWaveNodeStageAdvancer] - NODE 39: Stage DYNAMIC_VALUES. Initialisation retry timer triggered. Increased to 20000
2016-04-15 22:19:03.030 [DEBUG] [nitialization.ZWaveNodeStageAdvancer] - NODE 39: Node advancer - DYNAMIC_VALUES: queue length(0), free to send(false)
2016-04-15 22:19:03.031 [DEBUG] [nitialization.ZWaveNodeStageAdvancer] - NODE 39: Initialisation retry timer started 20000
2016-04-15 22:19:03.032 [DEBUG] [nitialization.ZWaveNodeStageAdvancer] - NODE 39: Node advancer: loop - DYNAMIC_VALUES try 2: stageAdvanced(false)
2016-04-15 22:19:03.032 [DEBUG] [nitialization.ZWaveNodeStageAdvancer] - NODE 39: Node advancer: DYNAMIC_VALUES - checking NO_OPERATION
2016-04-15 22:19:03.034 [DEBUG] [nitialization.ZWaveNodeStageAdvancer] - NODE 39: Node advancer: DYNAMIC_VALUES - checking DEVICE_RESET_LOCALLY
2016-04-15 22:19:03.038 [DEBUG] [nitialization.ZWaveNodeStageAdvancer] - NODE 39: Node advancer: DYNAMIC_VALUES - checking SWITCH_BINARY
2016-04-15 22:19:03.041 [DEBUG] [nitialization.ZWaveNodeStageAdvancer] - NODE 39: Node advancer: DYNAMIC_VALUES - found    SWITCH_BINARY
2016-04-15 22:19:03.043 [DEBUG] [nitialization.ZWaveNodeStageAdvancer] - NODE 39: Found 1 instances of SWITCH_BINARY
2016-04-15 22:19:03.045 [DEBUG] [dclass.ZWaveBinarySwitchCommandClass] - NODE 39: Creating new message for application command SWITCH_BINARY_GET
2016-04-15 22:19:03.048 [DEBUG] [nitialization.ZWaveNodeStageAdvancer] - NODE 39: Node advancer - queued packet. Queue length is 1
2016-04-15 22:19:03.052 [DEBUG] [ve.internal.protocol.ZWaveController] - Message queued. Queue length = 15. Queue={}
2016-04-15 22:19:03.057 [DEBUG] [nitialization.ZWaveNodeStageAdvancer] - NODE 39: Node advancer: DYNAMIC_VALUES - checking ZWAVE_PLUS_INFO
2016-04-15 22:19:03.058 [DEBUG] [nitialization.ZWaveNodeStageAdvancer] - NODE 39: Node advancer: DYNAMIC_VALUES - checking MANUFACTURER_SPECIFIC
2016-04-15 22:19:03.062 [DEBUG] [nitialization.ZWaveNodeStageAdvancer] - NODE 39: Node advancer: DYNAMIC_VALUES - checking BASIC
2016-04-15 22:19:03.065 [DEBUG] [nitialization.ZWaveNodeStageAdvancer] - NODE 39: Node advancer: DYNAMIC_VALUES - checking POWERLEVEL
2016-04-15 22:19:03.067 [DEBUG] [nitialization.ZWaveNodeStageAdvancer] - NODE 39: Node advancer: DYNAMIC_VALUES - queued 1 frames
2016-04-15 22:19:03.076 [WARN ] [ocol.ZWaveController$ZWaveSendThread] - NODE 39: Too many retries. Discarding message: Message: class=SendData[0x13], type=Request[0x00], priority=Get, dest=39, callback=23, payload=27 02 25 02 
2016-04-15 22:19:03.460 [DEBUG] [ocol.ZWaveController$ZWaveSendThread] - Took message from queue for sending. Queue length = 14
2016-04-15 22:19:03.461 [DEBUG] [wave.internal.protocol.SerialMessage] - Assembled message buffer = 01 09 00 13 24 02 84 08 25 1B 71 
2016-04-15 22:19:03.463 [DEBUG] [ing.zwave.handler.ZWaveSerialHandler] - NODE 36: Sending REQUEST Message = 01 09 00 13 24 02 84 08 25 1B 71 
2016-04-15 22:19:03.472 [DEBUG] [WaveSerialHandler$ZWaveReceiveThread] - Receive Message = 01 04 01 13 01 E8 
2016-04-15 22:19:03.474 [DEBUG] [ve.internal.protocol.ZWaveController] - Receive queue TAKE: Length=0
2016-04-15 22:19:03.475 [DEBUG] [wave.internal.protocol.SerialMessage] - Assembled message buffer = 01 04 01 13 01 E8 
2016-04-15 22:19:03.476 [DEBUG] [ve.internal.protocol.ZWaveController] - Process Message = 01 04 01 13 01 E8 
2016-04-15 22:19:03.477 [DEBUG] [ve.internal.protocol.ZWaveController] - Message: class=SendData[0x13], type=Response[0x01], priority=High, dest=255, callback=0, payload=01 
2016-04-15 22:19:03.478 [DEBUG] [l.serialmessage.SendDataMessageClass] - NODE 36: Sent Data successfully placed on stack.
2016-04-15 22:19:03.489 [DEBUG] [WaveSerialHandler$ZWaveReceiveThread] - Receive Message = 01 07 00 13 1B 00 00 03 F3 
2016-04-15 22:19:03.491 [DEBUG] [ve.internal.protocol.ZWaveController] - Receive queue TAKE: Length=0
2016-04-15 22:19:03.493 [DEBUG] [wave.internal.protocol.SerialMessage] - Assembled message buffer = 01 09 00 13 1B 00 00 03 00 00 FD 
2016-04-15 22:19:03.495 [DEBUG] [ve.internal.protocol.ZWaveController] - Process Message = 01 09 00 13 1B 00 00 03 00 00 FD 
2016-04-15 22:19:03.496 [DEBUG] [ve.internal.protocol.ZWaveController] - Message: class=SendData[0x13], type=Request[0x00], priority=High, dest=255, callback=0, payload=1B 00 00 03 
2016-04-15 22:19:03.496 [DEBUG] [l.serialmessage.SendDataMessageClass] - NODE 36: SendData Request. CallBack ID = 27, Status = Transmission complete and ACK received(0)
2016-04-15 22:19:03.498 [DEBUG] [.serialmessage.ZWaveCommandProcessor] - Checking transaction complete: Sent Message: class=SendData[0x13], type=Request[0x00], priority=Immediate, dest=36, callback=27, payload=24 02 84 08 
2016-04-15 22:19:03.499 [DEBUG] [.serialmessage.ZWaveCommandProcessor] - Checking transaction complete: Recv Message: class=SendData[0x13], type=Request[0x00], priority=High, dest=255, callback=0, payload=1B 00 00 03 
2016-04-15 22:19:03.500 [DEBUG] [.serialmessage.ZWaveCommandProcessor] - Checking transaction complete: class=SendData, callback id=27, expected=SendData, cancelled=false        transaction complete!
2016-04-15 22:19:03.500 [DEBUG] [ve.internal.protocol.ZWaveController] - Notifying event listeners: ZWaveTransactionCompletedEvent
2016-04-15 22:19:03.501 [DEBUG] [ding.zwave.handler.ZWaveThingHandler] - NODE 36: Got an event from Z-Wave network: ZWaveTransactionCompletedEvent
2016-04-15 22:19:03.501 [DEBUG] [nitialization.ZWaveNodeStageAdvancer] - NODE 36: Node advancer - PING: Transaction complete (SendData:Request) success(true)
2016-04-15 22:19:03.502 [DEBUG] [nitialization.ZWaveNodeStageAdvancer] - NODE 36: Node advancer - checking initialisation queue. Queue size 1.
2016-04-15 22:19:03.502 [DEBUG] [commandclass.ZWaveWakeUpCommandClass] - NODE 36: Went to sleep
2016-04-15 22:19:03.503 [DEBUG] [commandclass.ZWaveWakeUpCommandClass] - NODE 36: Is sleeping
2016-04-15 22:19:03.504 [DEBUG] [ocol.ZWaveController$ZWaveSendThread] - NODE 36: Response processed after 39ms/703ms.
2016-04-15 22:19:03.504 [DEBUG] [ocol.ZWaveController$ZWaveSendThread] - Took message from queue for sending. Queue length = 13
2016-04-15 22:19:03.505 [DEBUG] [commandclass.ZWaveWakeUpCommandClass] - NODE 36: Putting message SendData in wakeup queue.
2016-04-15 22:19:03.506 [DEBUG] [ocol.ZWaveController$ZWaveSendThread] - Took message from queue for sending. Queue length = 12
2016-04-15 22:19:03.507 [DEBUG] [wave.internal.protocol.SerialMessage] - Assembled message buffer = 01 09 00 13 27 02 25 02 25 15 D7 
```

**Comment by cdjackson** [comment]
Hmmm - I’d hoped I’d fixed the problem initialising this device a couple of days back :(  Can you supplier a longer log please.

**Comment by shorty707** [comment]
[node36_noxmldevice_devolo_kfob.txt](https://github.com/openhab/openhab2-addons/files/221756/node36_noxmldevice_devolo_kfob.txt)

well a real big one... since I am not sure what you are looking for

**Comment by cdjackson** [comment]
What version of the binding do you use? I thought this error was fixed :(

**Comment by shorty707** [comment]
can try and upgrade
currently its 157 | Active   |  80 | 2.0.0.201604121949    | ZWave Binding

**Comment by cdjackson** [comment]
3 days old - I think I updated this a couple of days back so hopefully this is fixed.

**Comment by shorty707** [comment]
Node 39 (Devolo POwer Switch) still the same... 
UI and Log say state changes ON / OFF 
the physical device shows no reaction

**Comment by cdjackson** [comment]
I don't think there's anything more I can do. I don't see any problem with the binding - it is sending the message to the device and the device is sending an ack. We also have a number of issues being discussed here, so I'm getting lost.

I suggest that problems with devices not working are discussed on the forum, and only if there's a bug in the binding identified do we raise an issue here. Otherwise this is turning into a forum, and it's not intended for this purpose.
